version: '3'
networks:
    default:
      external: 
        name: host
services:
    cassandra_to_rocksdb:
        build: ./docker
        volumes:
          - ./sst_diffs:/sst_diffs
          - ./src:/src
        command: python /src/create_sst_diffs.py bch_transformed bchn_transformed_20210219 192.168.243.101 192.168.243.102 192.168.243.103 192.168.243.104 192.168.243.105 192.168.243.106 192.168.243.107 192.168.243.108 --table cluster_incoming_relations --splitsize 100
          

